export const MADLIBS_DATA = [
  {
    id: 1,
    blanks: [
      "plural noun",
      "adverb",
      "verb",
      "article of clothing",
      "body part",
      "adjective",
      "noun",
      "plural noun",
      "another body part",
      "plural noun",
      "another body part",
      "noun",
      "noun",
      "verb ending in 'ing'",
      "adjective",
      "adjective",
      "verb",
    ],
    title: "How to Date the Coolest Guy/Girl in School",
    value: [
      "It's simple. Turn the ",
      ". Make him/her want ",
      " to date you. Make sure you're always dressed to ",
      ". Each and every day, wear a/an ",
      " that you know shows off your ",
      " to ",
      " advantage and make your ",
      " look like a million ",
      ". Even if the two of you make meaningful ",
      " contact, don't admit it. No hugs or ",
      ". Just shake his/her ",
      " firmly. And remember, when he/she asks you out, even though a chill may run down your ",
      " and you can't stop your ",
      " from ",
      ", just play it ",
      ". Take a long pause before answering in a very ",
      " voice. \"I'll have to ",
      ' it over."',
      0,
    ],
  },
  {
    id: 2,
    blanks: [
      "noun",
      "adjective",
      "verb",
      "adverb",
      "noun",
      "adjective",
      "plural noun",
      "plural noun",
      "plural noun",
      "part of the body",
      "noun",
      "noun",
      "noun",
      "noun",
      "part of the body",
    ],
    title: "Talk Like a Pirate",
    value: [
      "Ye can always pretend to be a bloodthirsty ",
      ", threatening everyone by waving yer ",
      " sword in the air, but until ye learn to ",
      " like a pirate, ye'll never be ",
      " accepted as an authentic ",
      ". So here's what ye do: Cleverly work into yer daily conversations ",
      ' pirate phrases such as "Ahoy there, ',
      ',""Avast, ye ',
      '," and "Shiver me ',
      ".\" Remember to drop all yer gs when ye say such words as sailin', spittin', and fightin'. This will give ye a/an ",
      " start to being recognized as a swashbucklin' ",
      ". Once ye have the lingo down pat, it helps to wear a three-cornered ",
      " on yer head, stash a/an ",
      " in yer pants, and keep a/an ",
      " perched atop yer ",
      ". Aye, now ye be a real pirate!",
      0,
    ],
  },
  {
    id: 3,
    blanks: [
      "adjective",
      "verb",
      "verb",
      "verb",
      "plural noun",
      "verb",
      "verb",
      "past tense verb",
      "plural noun",
      "adjective",
      "verb",
      "plural noun",
      "noun",
      "verb",
      "past tense verb",
      "noun",
      "noun",
      "noun",
      "past tense verb",
      "adjective",
      "past tense verb",
      "past tense verb",
      "noun",
      "past tense verb",
    ],
    title: "Three Little Pigs",
    value: [
      "Once up a time, there were three ",
      ' pigs. One day, their mother said, "You are all grown up and must ',
      ' on your own." So they left to ',
      " their houses. The first little pig wanted only to ",
      " all day and quickly built his house out of ",
      ". The second little pig wanted to ",
      " and ",
      " all day so he ",
      " his house with ",
      ". The third ",
      " pig knew the wolf lived nearby and worked hard to ",
      " his house out of ",
      ". One day, the wolf knocked on the first pig's ",
      ". \"Let me in or I'll ",
      " your house down!\" The pig didn't, so the wolf ",
      " down the ",
      ". The wolf knocked on the second pig's ",
      ". \"Let me in or I'll blow your ",
      " down!\" The pig didn't, so the wolf ",
      " down the house. Then the wolf knocked on the third ",
      " pig's door. \"Let me in or I'll blow your house down!\" The little pig didn't so the wolf ",
      " and ",
      ". He could not blow the house down. All the pigs went to live in the ",
      " house and they all ",
      " happily ever after.",
      0,
    ],
  },
  {
    id: 4,
    blanks: ["adjective", "verb", "verb", "verb"],
    title: "Test Madlib",
    value: [
      "Once up a time, there were three ",
      ' pigs. One day, their mother said, "You are all grown up and must ',
      ' on your own." So they left to ',
      " their houses. The first little pig wanted only to ",
      0,
    ],
  },
];
